/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function closeWispSession(sessionId: number): void

export declare function feedWispData(sessionId: number, data: Buffer): void

export declare function routeUpgradeCallbacks(head: Buffer, remoteIp: string, remotePort: number, url: string, wispVersion: number, optionsJson: string, onSend: (arg: Buffer) => void, onClose: () => void, onBlocked?: ((arg: string) => void) | undefined | null): number

export declare function routeUpgradeNative(fd: number, head: Buffer, remoteIp: string, remotePort: number, url: string, wispVersion: number, optionsJson: string): void

export declare function routeUpgradePipe(head: Buffer, remoteIp: string, remotePort: number, url: string, wispVersion: number, optionsJson: string): number

export declare function routeUpgradeTcpPipe(head: Buffer, remoteIp: string, remotePort: number, url: string, wispVersion: number, optionsJson: string): number

export declare function setGlobalOptions(optionsJson: string): void
