/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewtabRouteImport } from './routes/newtab'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as BaninfoRouteImport } from './routes/baninfo'
import { Route as BanRouteImport } from './routes/ban'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const NewtabRoute = NewtabRouteImport.update({
  id: '/newtab',
  path: '/newtab',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BaninfoRoute = BaninfoRouteImport.update({
  id: '/baninfo',
  path: '/baninfo',
  getParentRoute: () => rootRouteImport,
} as any)
const BanRoute = BanRouteImport.update({
  id: '/ban',
  path: '/ban',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/ban': typeof BanRoute
  '/baninfo': typeof BaninfoRoute
  '/benchmarks': typeof BenchmarksRoute
  '/bookmarks': typeof BookmarksRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/newtab': typeof NewtabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/ban': typeof BanRoute
  '/baninfo': typeof BaninfoRoute
  '/benchmarks': typeof BenchmarksRoute
  '/bookmarks': typeof BookmarksRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/newtab': typeof NewtabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/ban': typeof BanRoute
  '/baninfo': typeof BaninfoRoute
  '/benchmarks': typeof BenchmarksRoute
  '/bookmarks': typeof BookmarksRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/newtab': typeof NewtabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apps'
    | '/ban'
    | '/baninfo'
    | '/benchmarks'
    | '/bookmarks'
    | '/extensions'
    | '/history'
    | '/newtab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apps'
    | '/ban'
    | '/baninfo'
    | '/benchmarks'
    | '/bookmarks'
    | '/extensions'
    | '/history'
    | '/newtab'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apps'
    | '/ban'
    | '/baninfo'
    | '/benchmarks'
    | '/bookmarks'
    | '/extensions'
    | '/history'
    | '/newtab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppsRoute: typeof AppsRoute
  BanRoute: typeof BanRoute
  BaninfoRoute: typeof BaninfoRoute
  BenchmarksRoute: typeof BenchmarksRoute
  BookmarksRoute: typeof BookmarksRoute
  ExtensionsRoute: typeof ExtensionsRoute
  HistoryRoute: typeof HistoryRoute
  NewtabRoute: typeof NewtabRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/newtab': {
      id: '/newtab'
      path: '/newtab'
      fullPath: '/newtab'
      preLoaderRoute: typeof NewtabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baninfo': {
      id: '/baninfo'
      path: '/baninfo'
      fullPath: '/baninfo'
      preLoaderRoute: typeof BaninfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ban': {
      id: '/ban'
      path: '/ban'
      fullPath: '/ban'
      preLoaderRoute: typeof BanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppsRoute: AppsRoute,
  BanRoute: BanRoute,
  BaninfoRoute: BaninfoRoute,
  BenchmarksRoute: BenchmarksRoute,
  BookmarksRoute: BookmarksRoute,
  ExtensionsRoute: ExtensionsRoute,
  HistoryRoute: HistoryRoute,
  NewtabRoute: NewtabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
