/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as BanRouteImport } from './routes/ban'
import { Route as BaninfoRouteImport } from './routes/baninfo'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CheckfiltersRouteImport } from './routes/checkfilters'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as NewtabRouteImport } from './routes/newtab'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const BanRoute = BanRouteImport.update({
  id: '/ban',
  path: '/ban',
  getParentRoute: () => rootRouteImport,
} as any)
const BaninfoRoute = BaninfoRouteImport.update({
  id: '/baninfo',
  path: '/baninfo',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckfiltersRoute = CheckfiltersRouteImport.update({
  id: '/checkfilters',
  path: '/checkfilters',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NewtabRoute = NewtabRouteImport.update({
  id: '/newtab',
  path: '/newtab',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/ban': typeof BanRoute
  '/baninfo': typeof BaninfoRoute
  '/bookmarks': typeof BookmarksRoute
  '/checkfilters': typeof CheckfiltersRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/newtab': typeof NewtabRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/ban': typeof BanRoute
  '/baninfo': typeof BaninfoRoute
  '/bookmarks': typeof BookmarksRoute
  '/checkfilters': typeof CheckfiltersRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/newtab': typeof NewtabRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/ban': typeof BanRoute
  '/baninfo': typeof BaninfoRoute
  '/bookmarks': typeof BookmarksRoute
  '/checkfilters': typeof CheckfiltersRoute
  '/extensions': typeof ExtensionsRoute
  '/history': typeof HistoryRoute
  '/newtab': typeof NewtabRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/ban'
    | '/baninfo'
    | '/bookmarks'
    | '/checkfilters'
    | '/extensions'
    | '/history'
    | '/newtab'
    | '/settings'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/ban'
    | '/baninfo'
    | '/bookmarks'
    | '/checkfilters'
    | '/extensions'
    | '/history'
    | '/newtab'
    | '/settings'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/ban'
    | '/baninfo'
    | '/bookmarks'
    | '/checkfilters'
    | '/extensions'
    | '/history'
    | '/newtab'
    | '/settings'
    | '/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  BanRoute: typeof BanRoute
  BaninfoRoute: typeof BaninfoRoute
  BookmarksRoute: typeof BookmarksRoute
  CheckfiltersRoute: typeof CheckfiltersRoute
  ExtensionsRoute: typeof ExtensionsRoute
  HistoryRoute: typeof HistoryRoute
  NewtabRoute: typeof NewtabRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ban': {
      id: '/ban'
      path: '/ban'
      fullPath: '/ban'
      preLoaderRoute: typeof BanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baninfo': {
      id: '/baninfo'
      path: '/baninfo'
      fullPath: '/baninfo'
      preLoaderRoute: typeof BaninfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkfilters': {
      id: '/checkfilters'
      path: '/checkfilters'
      fullPath: '/checkfilters'
      preLoaderRoute: typeof CheckfiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newtab': {
      id: '/newtab'
      path: '/newtab'
      fullPath: '/newtab'
      preLoaderRoute: typeof NewtabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  BanRoute: BanRoute,
  BaninfoRoute: BaninfoRoute,
  BookmarksRoute: BookmarksRoute,
  CheckfiltersRoute: CheckfiltersRoute,
  ExtensionsRoute: ExtensionsRoute,
  HistoryRoute: HistoryRoute,
  NewtabRoute: NewtabRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
